### ISSUE TITLE
Choose which log files to filter in runtime

### ISSUE THREAD

**Issue by jguisp** [tibagni/LogViewer#10]
**Is your feature request related to a problem? Please describe.**
When I load more than one log file like main, radio, system, etc, it's not possible to choose
which one will be filtered.

**Describe the solution you'd like**
When there's more than one log file loaded, I would like to choose which log file to filter (one or more).
For example, in a first analysis, I may want to search only main and events log, but after that I may want
to remove events log and add system log. I'd like to be able to do that on the fly, without needing to reload the files in LogViewer.

**Describe alternatives you've considered**
Consider adding some checkboxes that will allow the user to select which log files will be filtered.
The user will be able to select one or more.

**Comment by tibagni** [comment]
BETA with this change:
[LogViewer_1.61.App.zip](https://github.com/tibagni/LogViewer/files/2476400/LogViewer_1.61.App.zip)

**Comment by tibagni** [comment]
5272d710c947079d9cdfda1b8fb8ed1a6012f757
