### ISSUE TITLE
Deleting selected filter does not reflect on filtered logs

### ISSUE THREAD

**Issue by tibagni** [tibagni/LogViewer#21]
**Describe the bug**
When deleting a checked filter, the filters are not re-applied and the deleted filter continues to be applied

**To Reproduce**
1. Select 2 or more filters
2. Directly delete one selected filter
3. Filtered logs remain unchanged

**Expected behavior**
Deleted filter should be removed from filtered logs

**Comment by vifrn** [comment]
Also happens when deleting the whole filter group.

**Comment by tibagni** [comment]
fixed on f80b2b9c2cf77ef8ec722b8f7843182e0ba52c0b
