### ISSUE TITLE
When user loads a filter group from file, all unsaved filter groups are removed

### ISSUE THREAD

**Issue by vifrn** [tibagni/LogViewer#23]
**Description**
When the user loads a filter group from a file, all groups previously added are removed without a warning.

**To Reproduce**
1. Make sure you have at least one saved filter group
2. Open LogViewer and add one or more filter groups.
3. Click on Filters -> Open Filter... and select your saved filter group file.
4. Check that all previous groups were deleted.

**Expected behavior**
The filter group you've just loaded is below the previous filter groups you added.

**Comment by tibagni** [comment]
b6d8eb785f2ae1acd074702e2abbd6ea10d8d768
