### ISSUE TITLE
Background color change.

### ISSUE THREAD

**Issue by rbresil** [tibagni/LogViewer#7]
**Is your feature request related to a problem? Please describe.**
Currently the LogViewer only has a White background. 
It would be nice if it provide a way to change the background color (for example, light gray)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tibagni** [comment]
Added New Look and feels
- 817db0418bc1b0a1a002db86d9d2eb10e6b8b9b9
- 1c91db1d4910ba17fa5fac16f46f7419def4a145
- 284426e03b743c5ad14e24b447c81134e1e2ef73
